FIT5042Assignment-war/src/fit5042/assignment/controllers/GroupController.java
package fit5042.assignment.controllers;

import javax.el.ELContext;
import javax.inject.Named;
import javax.enterprise.context.Dependent;
import javax.enterprise.context.RequestScoped;
import javax.faces.context.FacesContext;

/**
 *
 * 
 * @author Dongheng Zhan
 */
@Named(value = "groupController")
@RequestScoped
public class GroupController {
	private int groupId;

	public int getGroupId() {
		return groupId;
	}

	public void setUserId(int groupId) {
		this.groupId = groupId;
	}

	private fit5042.assignment.repository.entities.Groups groups;
	
	 public GroupController() {
	    
	    	groupId = Integer.valueOf(FacesContext.getCurrentInstance()
	                .getExternalContext()
	                .getRequestParameterMap()
	                .get("groupID"));
	       
	    	groups = getGroup();
	    }
	 
	 public fit5042.assignment.repository.entities.Groups getGroup() {
	        if (groups == null) {
	             
	            ELContext context
	                    = FacesContext.getCurrentInstance().getELContext();
	            GroupApplication app
	                    = (GroupApplication) FacesContext.getCurrentInstance()
	                            .getApplication()
	                            .getELResolver()
	                            .getValue(context, null, "groupApplication");
	           
	            return app.getGroupByID(groupId);
	        }
	        return groups;
	    }

}

FIT5042Assignment-war/src/fit5042/assignment/mbeans/ContactManagedBean.java
package fit5042.assignment.mbeans;

import fit5042.assignment.repository.ContactRepository;
import fit5042.assignment.repository.entities.Address;
import fit5042.assignment.repository.entities.ContactPerson;
import fit5042.assignment.repository.entities.Customer;

import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import java.io.Serializable;
import java.util.List;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;

/**
*
* 
* @author Dongheng Zhan
*/
@ManagedBean(name = "contactManagedBean")
@SessionScoped

public class ContactManagedBean implements Serializable {

   @EJB
   ContactRepository contactRepository;

   public String name;
   
   private Customer customerNew;
   
   public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}
	
   public ContactManagedBean() {
   }
   
   public List<Customer> getAllCustomers() {
       try {
           List<Customer> customers = contactRepository.getAllCustomers();
           return customers;
       } catch (Exception ex) {
           Logger.getLogger(ContactManagedBean.class.getName()).log(Level.SEVERE, null, ex);
       }
       return null;
   }

   public List<ContactPerson> getAllContacts() {
       try {
           List<ContactPerson> contacts = contactRepository.getAllContacts();
           return contacts;
       } catch (Exception ex) {
           Logger.getLogger(ContactManagedBean.class.getName()).log(Level.SEVERE, null, ex);
       }
       return null;
   }

   public void addContact(ContactPerson contact) {
       try {
           contactRepository.addContact(contact);
       } catch (Exception ex) {
           Logger.getLogger(ContactManagedBean.class.getName()).log(Level.SEVERE, null, ex);
       }
   }
   
   public Set<ContactPerson> searchContactByCustomerId(int customerId) {
       try {
           //retrieve contact person by id
           for (Customer customer : contactRepository.getAllCustomers()) {
               if (customer.getCustomerId() == customerId) {
                   return contactRepository.searchContactByCustomer(customer);
               }
           }
       } catch (Exception ex) {
           Logger.getLogger(ContactManagedBean.class.getName()).log(Level.SEVERE, null, ex);
       }

       return null;
   }

   /**
    * Search a Customer by Id
    */
   public ContactPerson searchContactById(int id) {
       try {
           return contactRepository.searchContactById(id);
       } catch (Exception ex) {
           Logger.getLogger(ContactManagedBean.class.getName()).log(Level.SEVERE, null, ex);
       }

       return null;
   }
  

   public void removeContact(int customerId) {
       try {
           contactRepository.removeContact(customerId);
       } catch (Exception ex) {
           Logger.getLogger(ContactManagedBean.class.getName()).log(Level.SEVERE, null, ex);
       }
   }

   public void editContact(ContactPerson contact) {
       try {
           String c = contact.getAddress().getStreetNumber();
           Address address = contact.getAddress();
           address.setStreetNumber(c);
           contact.setAddress(address);

           contactRepository.editContact(contact);

           FacesContext.getCurrentInstance().addMessage(null, new FacesMessage("Contact has been updated succesfully"));
       } catch (Exception ex) {
           Logger.getLogger(ContactManagedBean.class.getName()).log(Level.SEVERE, null, ex);
       }
   }

   public void addContact(fit5042.assignment.controllers.Contact localContact) {
       //convert this newProperty which is the local property to entity property
       ContactPerson contact = convertContactToEntity(localContact);

       try {
           contactRepository.addContact(contact);
       } catch (Exception ex) {
           Logger.getLogger(ContactManagedBean.class.getName()).log(Level.SEVERE, null, ex);
       }
   }
   
   public void addContact(fit5042.assignment.controllers.Contact localContact,int userId) {
       //convert this newProperty which is the local property to entity property
       ContactPerson contact = convertContactToEntity(localContact,userId);

       try {
           contactRepository.addContact(contact);
       } catch (Exception ex) {
           Logger.getLogger(ContactManagedBean.class.getName()).log(Level.SEVERE, null, ex);
       }
   }
	  
	  private ContactPerson convertContactToEntity(fit5042.assignment.controllers.Contact localContact) {
	        
	        ContactPerson contact = new ContactPerson(); //entity
	        String streetNumber = localContact.getStreetNumber();
	        String streetAddress = localContact.getStreetAddress();
	        String suburb = localContact.getSuburb();
	        String postcode = localContact.getPostcode();
	        String state = localContact.getState();
	        Address address = new Address(streetNumber, streetAddress, suburb, postcode, state);
	        String customerstreetNumber = localContact.getCustomerstreetNumber();
	        String customerstreetAddress = localContact.getCustomerstreetAddress();
	        String customersuburb = localContact.getCustomersuburb();
	        String customerpostcode = localContact.getCustomerpostcode();
	        String customerstate = localContact.getCustomerstate();
	        Address customeraddress = new Address(customerstreetNumber, customerstreetAddress, customersuburb, customerpostcode, customerstate);
	        contact.setAddress(address);
	        contact.setEmail(localContact.getEmail());
	        contact.setName(localContact.getName());
	        contact.setPhoneNumber(localContact.getPhoneNumber());
	        contact.setConactPersonId(localContact.getConactPersonId());
	        contact.setGender(localContact.getGender());
	        contact.setTags(localContact.getTags());
	        contact.setUserId(localContact.getUserId());
	        /*int customerId = localContact.getConactPersonId();
	        String customername = localContact.getCustomerName();
	        String customerEmail = localContact.getCustomerEmail();
	        String typeOfIndustry = localContact.getTypeOfIndustry();
	        int numberOfOrders = localContact.getNumberOfOrders();
	        String userType = localContact.getUserType();
	        Set<String> customertags = localContact.getCustomertags();*/
	        String[] nameArray = {}; 
	        nameArray = name.split("\\-");
	        int idd = Integer.parseInt(nameArray[0].trim());
	         customerNew  = new Customer();
	        try {
	        for (Customer customer : contactRepository.getAllCustomers())
	        { 
	        	if (customer.getCustomerId() == idd )
	            {   
	        	   customerNew = customer; 
	            }
	        }
	        }catch (Exception ex) {
	            Logger.getLogger(ContactManagedBean.class.getName()).log(Level.SEVERE, null, ex);
	        }
	       /* Customer customer = new fit5042.assignment.repository.entities.Customer( Integer.parseInt(nameArray[0]),customeraddress, numberOfOrders ,customername, typeOfIndustry, customerEmail,
	    			userType,customertags);*/
	        
	        if (customerNew.getCustomerId() == 0) {
	        	customerNew = null;
	        }
	        contact.setCustomer(customerNew);
	        return contact;
	    }
	  
	  private ContactPerson convertContactToEntity(fit5042.assignment.controllers.Contact localContact, int userId) {
	        
	        ContactPerson contact = new ContactPerson(); //entity
	        String streetNumber = localContact.getStreetNumber();
	        String streetAddress = localContact.getStreetAddress();
	        String suburb = localContact.getSuburb();
	        String postcode = localContact.getPostcode();
	        String state = localContact.getState();
	        Address address = new Address(streetNumber, streetAddress, suburb, postcode, state);
	        String customerstreetNumber = localContact.getCustomerstreetNumber();
	        String customerstreetAddress = localContact.getCustomerstreetAddress();
	        String customersuburb = localContact.getCustomersuburb();
	        String customerpostcode = localContact.getCustomerpostcode();
	        String customerstate = localContact.getCustomerstate();
	        Address customeraddress = new Address(customerstreetNumber, customerstreetAddress, customersuburb, customerpostcode, customerstate);
	        contact.setAddress(address);
	        contact.setEmail(localContact.getEmail());
	        contact.setName(localContact.getName());
	        contact.setPhoneNumber(localContact.getPhoneNumber());
	        contact.setConactPersonId(localContact.getConactPersonId());
	        contact.setGender(localContact.getGender());
	        contact.setTags(localContact.getTags());
	        contact.setUserId(userId);
	        /*int customerId = localContact.getConactPersonId();
	        String customername = localContact.getCustomerName();
	        String customerEmail = localContact.getCustomerEmail();
	        String typeOfIndustry = localContact.getTypeOfIndustry();
	        int numberOfOrders = localContact.getNumberOfOrders();
	        String userType = localContact.getUserType();
	        Set<String> customertags = localContact.getCustomertags();*/
	        String[] nameArray = {}; 
	        nameArray = name.split("\\-");
	        int idd = Integer.parseInt(nameArray[0].trim());
	         customerNew  = new Customer();
	        try {
	        for (Customer customer : contactRepository.getAllCustomers())
	        { 
	        	if (customer.getCustomerId() == idd )
	            {   
	        	   customerNew = customer; 
	            }
	        }
	        }catch (Exception ex) {
	            Logger.getLogger(ContactManagedBean.class.getName()).log(Level.SEVERE, null, ex);
	        }

FIT5042Assignment-war/src/fit5042/assignment/mbeans/TypeManagedBean.java
package fit5042.assignment.mbeans;

import fit5042.assignment.repository.TypeOfIndustryRepository;
import fit5042.assignment.repository.entities.TypeOfIndustry;
import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.servlet.http.HttpSession;

/**
*
* 
* @author Dongheng Zhan
*/
@ManagedBean(name = "typeManagedBean")
@SessionScoped
public class TypeManagedBean implements Serializable{
	
	@EJB
	TypeOfIndustryRepository typeRepository;
	

	public TypeManagedBean() {
    }

    public List<TypeOfIndustry> getAllTypes() {
        try {
            List<TypeOfIndustry> types = typeRepository.getAllTypes();
            return types;
        } catch (Exception ex) {
            Logger.getLogger(TypeManagedBean.class.getName()).log(Level.SEVERE, null, ex);
        }
        return null;
    }
    
    public void addType(TypeOfIndustry type) {
        try {
            typeRepository.addType(type);
        } catch (Exception ex) {
            Logger.getLogger(TypeManagedBean.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public TypeOfIndustry searchTypeById(int id) {
        try {
            return typeRepository.searchTypeById(id);
        } catch (Exception ex) {
            Logger.getLogger(TypeManagedBean.class.getName()).log(Level.SEVERE, null, ex);
        }

        return null;
    }
    
    public void removeType(int typeId) {
        try {
            typeRepository.removeType(typeId);
        } catch (Exception ex) {
            Logger.getLogger(TypeManagedBean.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void editType(TypeOfIndustry type) {
        try {

            typeRepository.editType(type);

            FacesContext.getCurrentInstance().addMessage(null, new FacesMessage("Type has been updated succesfully"));
        } catch (Exception ex) {
            Logger.getLogger(TypeManagedBean.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void addType(fit5042.assignment.controllers.Type localType) {
        //convert this newProperty which is the local property to entity property
        TypeOfIndustry type = convertTypeToEntity(localType);

        try {
            typeRepository.addType(type);
        } catch (Exception ex) {
            Logger.getLogger(TypeManagedBean.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private TypeOfIndustry convertTypeToEntity(fit5042.assignment.controllers.Type localType) {
        
        TypeOfIndustry type = new TypeOfIndustry();
        type.setTypeId(localType.getTypeId());
        type.setType(localType.getTypeOfIndustry());
        type.setTags(localType.getTags());
        return type;
    }


}

FIT5042Assignment-war/src/fit5042/assignment/mbeans/UsersManagedBean.java
package fit5042.assignment.mbeans;

import fit5042.assignment.repository.UserRepository;
import fit5042.assignment.repository.entities.Users;

import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.faces.application.FacesMessage;
import javax.faces.context.ExternalContext;
import javax.faces.context.ExternalContextWrapper;
import javax.faces.context.FacesContext;
import javax.servlet.http.HttpSession;

/**
*
* 
* @author Dongheng Zhan
*/
@ManagedBean(name = "usersManagedBean")
@SessionScoped
public class UsersManagedBean implements Serializable{
	
	@EJB
	UserRepository userRepository;
	

	public UsersManagedBean() {
    }

    public List<Users> getAllUsers() {
        try {
            List<Users> users = userRepository.getAllUsers();
            return users;
        } catch (Exception ex) {
            Logger.getLogger(UsersManagedBean.class.getName()).log(Level.SEVERE, null, ex);
        }
        return null;
    }
    
    public void addUser(Users user) {
        try {
            userRepository.addUser(user);
        } catch (Exception ex) {
            Logger.getLogger(UsersManagedBean.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public Users searchUsersById(int id) {
        try {
            return userRepository.searchUsersById(id);
        } catch (Exception ex) {
            Logger.getLogger(UsersManagedBean.class.getName()).log(Level.SEVERE, null, ex);
        }

        return null;
    }
    
    public void removeUser(int userId) {
        try {
        	userRepository.removeUser(userId);
        } catch (Exception ex) {
            Logger.getLogger(UsersManagedBean.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void editUsers(Users user) {
        try {

            userRepository.editUsers(user);

            FacesContext.getCurrentInstance().addMessage(null, new FacesMessage("User has been updated succesfully"));
        } catch (Exception ex) {
            Logger.getLogger(UsersManagedBean.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void addUser(fit5042.assignment.controllers.Users localUser) {
        //convert this newProperty which is the local property to entity property
    	Users user = convertUsersToEntity(localUser);

        try {
            userRepository.addUser(user);
        } catch (Exception ex) {
            Logger.getLogger(UsersManagedBean.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private Users convertUsersToEntity(fit5042.assignment.controllers.Users localUser) {
        
    	Users user = new Users();
        user.setUserId(localUser.getUserId());
        user.setUserName(localUser.getUserName());
        user.setPassword(localUser.getPassword());
        user.setTags(localUser.getTags());
        return user;
    }
    
    public String getUserName()
    {
    	
    	return (String) FacesContext.getCurrentInstance().getExternalContext().getRemoteUser();
    }
    public String name() {
    	String name = "staff";
    	return name;
    }

}

FIT5042Assignment-war/WebContent/admin/Cadd.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:p="http://primefaces.org/ui"
	xmlns:pt="http://xmlns.jcp.org/jsf/passthrough">
<h:head>
	<h:outputStylesheet library="css" name="bootstrap.min.css"></h:outputStylesheet>
	<title>#{titleController.pageTitle}</title>
</h:head>
<h:body>
	<div class="container">
		<div class="navbar navbar-inverse">
			<div class="navbar-brand">#{titleController.pageTitle} - Add
				Contact Person</div>
		</div>
		<div>
			<f:view>
				<h:form>
					<h1>
						<h:outputText value="Create" />
					</h1>
					<table class="table table-bordered ">

						<tr class="#{!streetNumber.valid ? 'has-error' : 'none'}">
							<td width="200"><h:outputLabel value="streetNumber"
									for="streetNumber" /></td>
							<td><h:inputText id="streetNumber"
									value="#{contact.streetNumber}" title="streetNumber"
									required="true"
									requiredMessage="Please enter the street number!"
									validatorMessage="Please enter a street number between 1 and 1000"
									converterMessage="Please enter a number" pt:placeholder="900">
									<f:convertNumber integerOnly="true" />
									<f:validateLongRange minimum="1" maximum="1000" />
								</h:inputText> <br /> <h:message for="streetNumber"
									class="#{!streetNumber.valid ? 'label label-warning' : 'none'}" />
							</td>
						</tr>

						<tr class="#{!streetAddress.valid ? 'has-error' : 'none'}">
							<td><h:outputLabel value="streetAddress" for="streetAddress" />
							</td>
							<td><h:inputText id="streetAddress"
									value="#{contact.streetAddress}" title="streetAddress"
									required="true"
									requiredMessage="Please enter the street address!"
									pt:placeholder="Dandenong Rd" /> <br /> <h:message
									for="streetAddress"
									class="#{!streetAddress.valid ? 'label label-warning' : 'none'}" />
							</td>

						</tr>

						<tr class="#{!suburb.valid ? 'has-error' : 'none'}">
							<td><h:outputLabel value="suburb" for="suburb" /></td>
							<td><h:inputText id="suburb" value="#{contact.suburb}"
									title="suburb" required="true"
									requiredMessage="Please enter the suburb!"
									pt:placeholder="Caulfield East" /> <br /> <h:message
									for="suburb"
									class="#{!suburb.valid ? 'label label-warning' : 'none'}" /></td>

						</tr>

						<tr class="#{!state.valid ? 'has-error' : 'none'}">
							<td><h:outputLabel value="state" for="state" /></td>
							<td><h:inputText id="state" value="#{contact.state}"
									title="state" size="3" required="true"
									requiredMessage="Please enter the state!" pt:placeholder="VIC" />
								<br /> <h:message for="state"
									class="#{!state.valid ? 'label label-warning' : 'none'}" /></td>

						</tr>
						<tr class="#{!postcode.valid ? 'has-error' : 'none'}">
							<td><h:outputLabel value="postcode" for="postcode" /></td>
							<td><h:inputText id="postcode" value="#{contact.postcode}"
									title="postcode" required="true"
									requiredMessage="Please enter the postcode!"
									validatorMessage="Please enter a postcode between 0200 and 4700"
									converterMessage="Please enter a number" pt:placeholder="3145">
									<f:convertNumber integerOnly="true" />
									<f:validateLongRange minimum="200" maximum="4700" />
								</h:inputText> <br /> <h:message for="postcode"
									class="#{!postcode.valid ? 'label label-warning' : 'none'}" />
							</td>

						</tr>
						<tr class="#{!name.valid ? 'has-error' : 'none'}">
							<td><h:outputLabel value="Name" for="name" /></td>
							<td><h:inputText id="name" value="#{contact.name}"
									title="Name" required="true"
									requiredMessage="Please enter the name!" pt:placeholder="ABC" />
								<br /> <h:message for="name"
									class="#{!name.valid ? 'label label-warning' : 'none'}" /></td>

						</tr>
						<tr class="#{!gender.valid ? 'has-error' : 'none'}">
							<td><h:outputLabel value="Gender" for="gender" /></td>
							<td><h:inputText id="gender" value="#{contact.gender}"
									title="Gender" required="true"
									requiredMessage="Please enter the gender!" pt:placeholder="M" />
								<br /> <h:message for="gender"
									class="#{!gender.valid ? 'label label-warning' : 'none'}" /></td>

						</tr>

						<tr class="#{!phoneNumber.valid ? 'has-error' : 'none'}">
							<td><h:outputLabel value="PhoneNumber:"
									for="phoneNumber" /></td>
							<td><h:inputText id="phoneNumber"
									value="#{contact.phoneNumber}" title="PhoneNumber"
									required="true"
									requiredMessage="Please enter the Phone Number!"
									validatorMessage="Invalide Phone Number"
									converterMessage="Please enter a Phone number" pt:placeholder="432657716">
									<f:validateLength minimum="9" maximum = "14" />
								</h:inputText> <br /> <h:message for="phoneNumber"
									class="#{!phoneNumber.valid ? 'label label-warning' : 'none'}" /></td>

						</tr>

						<tr class="#{!email.valid ? 'has-error' : 'none'}">
							<td><h:outputLabel value="Email" for="email" /></td>
							<td><h:inputText id="email" value="#{contact.email}"
									title="Email" required="true"
									requiredMessage="Please enter the email!"
									pt:placeholder="ABC@gmail.com" 
									validatorMessage="Invalide Email">
							<f:validateRegex pattern="[\w\.-]*[a-zA-Z0-9_]@[\w\.-]*[a-zA-Z0-9]\.[a-zA-Z][a-zA-Z\.]*[a-zA-Z]" /></h:inputText> <br /> <h:message
									for="email"
									class="#{!email.valid ? 'label label-warning' : 'none'}" /></td>

						</tr>
						
						<tr>
							<td><h:outputLabel value="User ID:"
									for="userid" /></td>
							<td><h:inputText id="userid"
									value="#{contact.userId}" title="UserId"
									required="true"
									requiredMessage="Please enter the User ID!"
									validatorMessage="User Id must be number"
									converterMessage="Please enter a number" pt:placeholder="1">
									<f:validateLongRange minimum="1" />
								</h:inputText> <br /> <h:message for="userid"
									class="#{!userid.valid ? 'label label-warning' : 'none'}" /></td>

						</tr>
						
						<tr>
							<td><h:outputLabel value="Customer:" for="customer" /></td>
							<td>
                            <h:selectOneMenu id="customer" value="#{contactManagedBean.name}">
                                <f:selectItem itemValue="#{null}" itemLabel="--select--" />
                                <f:selectItems value="#{contactManagedBean.allCustomers}" var="c"  
                                               itemLabel="#{c.toString()}" itemValue="#{c}" />
                            </h:selectOneMenu>
                        </td>
						</tr>
						
					</table>

					<h:commandButton id="submit" value="Submit"
						action="#{addContact.addContact(contact)}"
						class="btn btn-primary" />
					<h:link id="close" value="Close" outcome="Contact.xhtml"
						class="btn btn-primary" />

				</h:form>

			</f:view>
		</div>
	</div>

</h:body>
</html>

FIT5042Assignment-war/WebContent/admin/Gadd.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:p="http://primefaces.org/ui"
	xmlns:pt="http://xmlns.jcp.org/jsf/passthrough">
<h:head>
	<h:outputStylesheet library="css" name="bootstrap.min.css"></h:outputStylesheet>
	<title>#{titleController.pageTitle}</title>
</h:head>
<h:body>
	<div class="container">
		<div class="navbar navbar-inverse">
			<div class="navbar-brand">#{titleController.pageTitle} - Add
				User</div>
		</div>
		<div>
			<f:view>
				<h:form>
					<h1>
						<h:outputText value="Create" />
					</h1>
					<table class="table table-bordered ">
					
						<tr>
							<td><h:outputLabel value="User Name"
									for="User" /></td>
							<td><h:selectOneMenu id="user"
									value="#{groups.userName}" title="User"
									required="true"
									requiredMessage="Please select the User!">
									  <f:selectItem itemValue="#{null}" itemLabel="--select--" />
                                <f:selectItems value="#{usersManagedBean.allUsers}" var="u"  
                                               itemLabel="#{u.userName}" itemValue="#{u.userName}" />
								</h:selectOneMenu><br /> <h:message for="user"
									class="#{!user.valid ? 'label label-warning' : 'none'}" /></td>

						</tr>
                    
						
						<tr>
							<td><h:outputLabel value="Group:"
									for="group" /></td>
							<td><h:selectOneMenu id="group"
									value="#{groups.groupName}" title="Group"
									required="true"
									requiredMessage="Please select the group!" >
									<f:selectItem itemValue="#{null}" itemLabel="--select--" />
									<f:selectItem itemValue="admin" itemLabel = "Admin"/>
									<f:selectItem itemValue="staff" itemLabel = "Staff"/>
								</h:selectOneMenu><br /> <h:message for="group"
									class="#{!group.valid ? 'label label-warning' : 'none'}" /></td>

						</tr>
					</table>

					<h:commandButton id="submit" value="Submit"
						action="#{addGroup.addGroup(groups)}"
						class="btn btn-primary" />
						
						<h:link id="close" value="Close" outcome="Group.xhtml"
						class="btn btn-primary" />
						

				</h:form>

			</f:view>
		</div>
	</div>

</h:body>
</html>

FIT5042Assignment-war/WebContent/admin/navigation.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html"> 

<h:head>
</h:head> 
<body> 
  <a href="home.xhtml">Home |</a>
  <a href="Customer.xhtml">Customer |</a>
  <a href="Contact.xhtml">Contact Person |</a>
  <a href="Type.xhtml">Type Of Industry |</a>
  <a href="Uhome.xhtml">Users |</a>
  <a href="back.xhtml">Log Out</a>

</body> 
</html>